### ISSUE TITLE
ACF Naming Conventions 

### ISSUE THREAD

**Issue by MikaCaldera** [mirandacreative/mfm#7]
https://github.com/mirandacreative/mfm/blob/6a2b326c005d7b858f08ec2674980d820bf37add/inc/parts/blurb.php#L7

Hello, 

I haven't looked through all the files but I want to make sure the naming conventions stay the same for the ACF fields on the dashboard as well as in the code.  

Example: 
 title = title
picture = image 

Let me know what you think. 

@pdxor @msrinteractive

**Comment by pdxor** [comment]
Ok I will conform to that pattern :)
